### ISSUE TITLE
Sequence crash at the begining of a sequence

### ISSUE THREAD

**Issue by light-scattering-io** [light-scattering-io/caqtus#62]
**Describe the bug**
Sometimes before a sequence starts it crashes for no apparent reason. It seems to be random because trying to restart the crashed sequence usually works. Usually we can tell the sequence will crash because we don't hear the click click of the AWG and then we have to wait for a few seconds before the sequence crashes

**To Reproduce**
Random unluck

**Screenshots**
![bug](https://github.com/user-attachments/assets/d82664b7-5d36-4023-bdfa-1cf33012ea15)
![image](https://github.com/user-attachments/assets/02cedacb-5960-4756-af67-ed4fb8ea5b6e)
![image](https://github.com/user-attachments/assets/4d285829-d5d1-4d87-a426-4dead32e4077)

**Additional context**

**Comment by damienBloch** [comment]
Should be fixed in v6.18.1
The issue appeared after adding a timeout of 5s for shot compilation.
This is usually long enough to compile a shot, except for the very first one, since the compilation needs to spawn a process pool, which take time.
